package andrew.com.riko.www.webviewproject.model;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
@DatabaseTable(tableName = "registration")
public class Registration {

    // id is generated by the database and set on the object automagically
    @DatabaseField(columnName="id",generatedId = true)
    private int id;
    @DatabaseField(columnName="city")
    private String city ;
    @DatabaseField(columnName="hospital")
    private String hospital ;
    @DatabaseField(columnName="division")
    private String division;
    @DatabaseField(columnName="year")
    private int year ;
    @DatabaseField(columnName="month")
    private int month ;
    @DatabaseField(columnName="day")
    private int day ;

    public Registration() {
        // needed by ormlite
    }

    public Registration(int id, String city, String hospital, String division, int year, int month, int day) {
        this.id = id;
        this.city = city;
        this.hospital = hospital;
        this.division = division;
        this.year = year;
        this.month = month;
        this.day = day;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getHospital() {
        return hospital;
    }

    public void setHospital(String hospital) {
        this.hospital = hospital;
    }

    public String getDivision() {
        return division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public int getMonth() {
        return month;
    }

    public void setMonth(int month) {
        this.month = month;
    }

    public int getDay() {
        return day;
    }

    public void setDay(int day) {
        this.day = day;
    }

    @Override
    public String toString() {
        return "Registration{" +
                "id=" + id +
                ", city='" + city + '\'' +
                ", hospital='" + hospital + '\'' +
                ", division='" + division + '\'' +
                ", year=" + year +
                ", month=" + month +
                ", day=" + day +
                '}';
    }
}
